### ISSUE TITLE
Can't group routes using different prefixes

### ISSUE THREAD

**Issue by hxdef2517** [dingo/api#1567]
| Q                 | A
| ----------------- | ---
| Bug?              | no|yes
| New Feature?      | no|yes
| Framework         | Laravel|Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 5.x.y|7.x.y

#### Actual Behaviour

I'm trying to group different route groups with different prefixes, but in the end only one prefix group is working.

#### Expected Behaviour
```
$api = app('Dingo\Api\Routing\Router');

$api->group(['version' => 'v1', 'prefix' => 'auth', 'domain' => env('APP_DOMAIN'), 'namespace' => 'App\\Http\\Controllers'], function($api) {

    $api->version('v1', ['middleware' => ['throttle:40', 'api']], function ($api) {

        $api->post('login', 'AuthController@login');
        ... Routes...
     });
});

$api->group(['version' => 'v1', 'prefix' => 'main', 'domain' => env('APP_DOMAIN'), 'namespace' => 'App\\Http\\Controllers'], function($api) {

    $api->version('v1', ['middleware' => ['throttle:40', 'api']], function ($api) {

        $api->post('/cables',                           'CablesController@postCreate');
        ... Routes...
     });
});
```

How to solve this ? I need exactly this kind of solution, using same domain and different route groups defined by prefixes. Thanks

**Comment by gazben** [comment]
@hxdef2517 Same problem here if I create a resource and a prefixed group with the same name.
Error message: 
```Argument 1 passed to Illuminate\Routing\RouteCollection::add() must be an instance of Illuminate\Routing\Route, null given```

Can you paste your error message? Is it the same?

**Comment by specialtactics** [comment]
Hey guys, I think this problem has been fixed with PR  https://github.com/dingo/api/pull/1555 ?

@hxdef2517 @gazben - Can you confirm?

**Comment by gazben** [comment]
@specialtactics Yes, it should be the fix.

**Comment by hxdef2517** [comment]
@gazben @specialtactics not fixed, if you guys know how to group routes under different prefixes and done it before for sure with dingo/api package, could you post here some example ? ( I've updated package to latest and still can't make it work. Everything is nice in this package except the ability to define other prefixes...

**Comment by specialtactics** [comment]
@hxdef2517 can you post an example of your route file (just the part that's the problem ideally), I've never had problems with routes.

Can you also post your route service provider file and your kernel.php

**Comment by hxdef2517** [comment]
@specialtactics its posted above, in expected behavior. So basically I have my main app routes and I have admin routes, I'd like to distribute these routes with different prefix, but can't group them in a way to make this work. I got my routes in php artisan api:routes but whenever I hit certain route, its always not found.

**Comment by hxdef2517** [comment]
@specialtactics I've posted an example in expected behavior in a post above. So basically I'd like to have two prefixes, one for my main app routes and another for admin routes, but wasn't able to do that. 

**My routes are working fine, but just with one prefix.**  If I add one more, the routes will be seen in php artisan api:routes but won't be able to access it, page not found for all the routes with different prefix

**Comment by specialtactics** [comment]
@hxdef2517 I was hoping you could actually give me your routes file so that I can reproduce the problem locally and debug. I can't immediately see anything wrong with your example (although as the first thing, I would try and group everything under one top level route group).

**Comment by hxdef2517** [comment]
@specialtactics The sample routes are displayed inside expected behavior above. Basically I have my app routes and admin routes and want to differentiate them using different prefixes. If I design in that way shown in example, I can see my routes inside a list (php artisan api:routes) but whenever I try to access them I receive Page not found all the time. Any example of using different route groups with different prefixes pls ?

**Comment by specialtactics** [comment]
@hxdef2517 I don't know if I am not being clear, but you will need to provide actual runnable code from here on out - at least for me to help you, otherwise it's just speculation on my behalf as to why it doesn't work. If on the other hand I can directly reproduce your problem, I'll be able to help you.

As I said I have done this many times and it works, so potentially there's a different way you need to write the routes, but it's hard for me to say exactly what you need to do differently if you don't show me your exact routes file.

**Comment by hxdef2517** [comment]
@specialtactics sorry I think my connection got issue, I've been trying to post the comment, then it never shown, thats why I posted few lol )))) anyway I'll post the route files here in awhile so that maybe you can check and see.

**Comment by hxdef2517** [comment]
@specialtactics thats the sample of my routes. I've also tried to init different routers with different parameters also no result.

**routes/web.php**

```
$api = app('Dingo\Api\Routing\Router');

$params = [
	'version' => 'v1',
	'prefix' => 'api',
	'domain' => env('APP_DOMAIN'),
	'namespace' => 'App\\Http\\Controllers',
];

$adminParams = [
    'version' => 'v1',
    'prefix' => 'admin',
    'domain' => env('APP_DOMAIN'),
    'namespace' => 'App\\Http\\Controllers',
];

$api->group($adminParams, function ($api) {

    $api->get('/some-route', function () {
        echo "asd";
    });
});

$api->group($params, function ($api) {

	$api->get('/some-route2', function () {
        echo "asd";
    });
});
```

**config/api.php**

```
<?php


return [

    /*
    |--------------------------------------------------------------------------
    | Standards Tree
    |--------------------------------------------------------------------------
    |
    | Versioning an API with Dingo revolves around content negotiation and
    | custom MIME types. A custom type will belong to one of three
    | standards trees, the Vendor tree (vnd), the Personal tree
    | (prs), and the Unregistered tree (x).
    |
    | By default the Unregistered tree (x) is used, however, should you wish
    | to you can register your type with the IANA. For more details:
    | https://tools.ietf.org/html/rfc6838
    |
    */

    'standardsTree' => env('API_STANDARDS_TREE', 'x'),

    /*
    |--------------------------------------------------------------------------
    | API Subtype
    |--------------------------------------------------------------------------
    |
    | Your subtype will follow the standards tree you use when used in the
    | "Accept" header to negotiate the content type and version.
    |
    | For example: Accept: application/x.SUBTYPE.v1+json
    |
    */

    'subtype' => env('API_SUBTYPE', 'api'),

    /*
    |--------------------------------------------------------------------------
    | Default API Version
    |--------------------------------------------------------------------------
    |
    | This is the default version when strict mode is disabled and your API
    | is accessed via a web browser. It's also used as the default version
    | when generating your APIs documentation.
    |
    */

    'version' => env('API_VERSION', 'v1'),

    /*
    |--------------------------------------------------------------------------
    | Default API Prefix
    |--------------------------------------------------------------------------
    |
    | A default prefix to use for your API routes so you don't have to
    | specify it for each group.
    |
    */

    'prefix' => env('API_PREFIX', 'api'),

    /*
    |--------------------------------------------------------------------------
    | Default API Domain
    |--------------------------------------------------------------------------
    |
    | A default domain to use for your API routes so you don't have to
    | specify it for each group.
    |
    */

    'domain' => env('API_DOMAIN', null),

    /*
    |--------------------------------------------------------------------------
    | Name
    |--------------------------------------------------------------------------
    |
    | When documenting your API using the API Blueprint syntax you can
    | configure a default name to avoid having to manually specify
    | one when using the command.
    |
    */

    'name' => env('API_NAME', null),

    /*
    |--------------------------------------------------------------------------
    | Conditional Requests
    |--------------------------------------------------------------------------
    |
    | Globally enable conditional requests so that an ETag header is added to
    | any successful response. Subsequent requests will perform a check and
    | will return a 304 Not Modified. This can also be enabled or disabled
    | on certain groups or routes.
    |
    */

    'conditionalRequest' => env('API_CONDITIONAL_REQUEST', true),

    /*
    |--------------------------------------------------------------------------
    | Strict Mode
    |--------------------------------------------------------------------------
    |
    | Enabling strict mode will require clients to send a valid Accept header
    | with every request. This also voids the default API version, meaning
    | your API will not be browsable via a web browser.
    |
    */

    'strict' => env('API_STRICT', false),

    /*
    |--------------------------------------------------------------------------
    | Debug Mode
    |--------------------------------------------------------------------------
    |
    | Enabling debug mode will result in error responses caused by thrown
    | exceptions to have a "debug" key that will be populated with
    | more detailed information on the exception.
    |
    */

    'debug' => env('API_DEBUG', true),

    /*
    |--------------------------------------------------------------------------
    | Generic Error Format
    |--------------------------------------------------------------------------
    |
    | When some HTTP exceptions are not caught and dealt with the API will
    | generate a generic error response in the format provided. Any
    | keys that aren't replaced with corresponding values will be
    | removed from the final response.
    |
    */

    'errorFormat' => [
        'message' => ':message',
        'errors' => ':errors',
        'code' => ':code',
        'status_code' => ':status_code',
        'debug' => ':debug',
    ],

    /*
    |--------------------------------------------------------------------------
    | API Middleware
    |--------------------------------------------------------------------------
    |
    | Middleware that will be applied globally to all API requests.
    |
    */

    'middleware' => [

    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Providers
    |--------------------------------------------------------------------------
    |
    | The authentication providers that should be used when attempting to
    | authenticate an incoming API request.
    |
    */

    'auth' => [

    ],

    /*
    |--------------------------------------------------------------------------
    | Throttling / Rate Limiting
    |--------------------------------------------------------------------------
    |
    | Consumers of your API can be limited to the amount of requests they can
    | make. You can create your own throttles or simply change the default
    | throttles.
    |
    */

    'throttling' => [

    ],

    /*
    |--------------------------------------------------------------------------
    | Response Transformer
    |--------------------------------------------------------------------------
    |
    | Responses can be transformed so that they are easier to format. By
    | default a Fractal transformer will be used to transform any
    | responses prior to formatting. You can easily replace
    | this with your own transformer.
    |
    */

    'transformer' => env('API_TRANSFORMER', Dingo\Api\Transformer\Adapter\Fractal::class),

    /*
    |--------------------------------------------------------------------------
    | Response Formats
    |--------------------------------------------------------------------------
    |
    | Responses can be returned in multiple formats by registering different
    | response formatters. You can also customize an existing response
    | formatter.
    |
    */

    'defaultFormat' => env('API_DEFAULT_FORMAT', 'json'),

    'formats' => [

        'json' => Dingo\Api\Http\Response\Format\Json::class,

    ],

];

```

**Comment by specialtactics** [comment]
@hxdef2517 I have put the exact example you gave without changing anything and it worked for me.

Maybe you are confused about API prefixes, that would be my only guess. The file api.php by default in laravel has a path prefix of /api (and it appears you have that configured in your dingo). So this means for you, the path would be

domain/api/api/some-route
and
domain/api/admin/some-route2

If you don't want the first api prefix, just remove it as a prefix in kernel.php and dingo.php config file (note that you will want to either remove web or give it its own prefix in this case so that it wont conflict).

**Comment by hxdef2517** [comment]
@specialtactics if I remove prefix from config file, I'm getting this error:
`Unable to boot ApiServiceProvider, configure an API domain or prefix.`
After googling it seems like its a must to have a prefix there. How did you manage to solve that ?

**Comment by specialtactics** [comment]
@hxdef2517 Just configure the API_DOMAIN as the error message implies. Note to leave out the "http://".

**Comment by hxdef2517** [comment]
@specialtactics yea finally solved by specifying domain and removing prefix. Thanks dude! 👍

**Comment by specialtactics** [comment]
Fantastic, glad to hear it @hxdef2517 !
