### ISSUE TITLE
jwt-auth and dingo/api responses

### ISSUE THREAD

**Issue by BRupholdt** [dingo/api#382]
I'm using jwt-auth which returns errors using Response::json from their filter.  
This causes dingo/api to error with Call to undefined method Illuminate\Http\JsonResponse::getFormatter()

I rewrote my own filters to work around dingo's limitations with responses but I really don't want to override another package.  Is there a way to make dingo/api let me return normal responses?

**Comment by BRupholdt** [comment]
Example route which causes this error
```php
Route::api('v2', function () {
	Route::get('me', ['before' => 'jwt-auth', function() {
		// jwt-auth filter returns error using Response::json which breaks dingo/api
		$user = JWTAuth::parseToken()->toUser();
		return $user;
	}]);
});
```

**Comment by devmark** [comment]
try to use 
~~~~
API::user()
~~~~

**Comment by BRupholdt** [comment]
The error occurs in the jwt-auth filter that comes as part of the jwt-auth package.  It works fine outside the api routes. I'm at a loss as to why response::json doesn't work with the api package.

**Comment by bweston92** [comment]
In order for dingo to set up the user you will need 'protected' => true on the Api/group.



—

**Comment by jrm2k6** [comment]
Same issue for me.

**Comment by jrm2k6** [comment]
Adding protected => true, doesn't fix anything.
API::user() has nothing to do with the issue.

**Comment by BRupholdt** [comment]
I finally tracked down my error.  I'd added a app::error function for catching JWTExceptions in global.php.  The response calls there were not prefixed with a backslash so were looking in the api namespace.  To make the issue worse, there was a stray character in function that was breaking the error stack so it never pointed to global.php.  

I got the bright idea to try catching the errors in global.php only to find I'd already done so.  That's how I found the typo.  Once corrected, the real issue was visible.  Calling Response from the global namespace solved the issue for me.

I almost gave up using dingo/api except that tymondesigns/jwt-auth recommended it so I knew it ought to be working.

**Comment by jameswagoner** [comment]
@BRupholdt Could you post a gist of your jw-auth filter or does simply enabling protection on a route work out of the box when JWT is configured as your authentication method?

**Comment by jameswagoner** [comment]
Looks like the fix is here: https://github.com/dingo/api/issues/369

A method was changed in JWTAuth but hasn't been updated here.

**Comment by jasonlewis** [comment]
You should be using the built-in JWT authentication which means you don't use the provided filter. Let Dingo handle it. I've pushed a fix for the latest JWTAuth version so it's on `0.8.*@dev`, will tag a release soon.

**Comment by jrm2k6** [comment]
I still have the same issue.
dingo: 0.8.*dev
jwt-auth: 0.4.2

Should I downgrade to 0.4.1?
What do you mean by 'don't use the provided filter'?
