### ISSUE TITLE
Non-api route problem

### ISSUE THREAD

**Issue by banandam** [dingo/api#997]
Non API dynamic routing not working, error message given below

{
  "message": "404 Not Found",
  "status_code": 404,
  "debug": {
    "line": 443,
    "file": "G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php",
    "class": "Symfony\Component\HttpKernel\Exception\NotFoundHttpException",
    "trace": [
      "#0 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(381): Laravel\Lumen\Application->handleDispatcherResponse(Array)",
      "#1 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(629): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()",
      "#2 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(382): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))",
      "#3 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\dingo\api\src\Routing\Adapter\Lumen.php(103): Laravel\Lumen\Application->dispatch(Object(Dingo\Api\Http\Request))",
      "#4 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\dingo\api\src\Routing\Router.php(574): Dingo\Api\Routing\Adapter\Lumen->dispatch(Object(Dingo\Api\Http\Request), 'v1')",
      "#5 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\dingo\api\src\Http\Middleware\Request.php(123): Dingo\Api\Routing\Router->dispatch(Object(Dingo\Api\Http\Request))",
      "#6 [internal function]: Dingo\Api\Http\Middleware\Request->Dingo\Api\Http\Middleware\{closure}(Object(Dingo\Api\Http\Request))",
      "#7 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\illuminate\pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Dingo\Api\Http\Request))",
      "#9 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\Api\Http\Request))",
      "#10 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\dingo\api\src\Http\Middleware\Request.php(124): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#11 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\dingo\api\src\Http\Middleware\Request.php(100): Dingo\Api\Http\Middleware\Request->sendRequestThroughRouter(Object(Dingo\Api\Http\Request))",
      "#12 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))",
      "#13 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\illuminate\pipeline\Pipeline.php(124): call_user_func_array(Array, Array)",
      "#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))",
      "#15 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#16 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))",
      "#17 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))",
      "#18 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(626): Illuminate\Pipeline\Pipeline->then(Object(Closure))",
      "#19 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(382): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))",
      "#20 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(327): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))",
      "#21 G:\anandam_023ac09\projects\LaravelBase\trunk\lumen\public\index.php(28): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))",
      "#22 {main}"
    ]
  }
}

$api = $app->make('Dingo\Api\Routing\Router');

// working
$app->get('/', function () use ($app) {
    return $app->version();
});
// working
$app->get('robots.txt', function () use ($app) {
    return config('site.robots');
});
// Not working [Non api route]
// /public/img/small/user/11.6512bd43d9caa6e02c990b0a82652dca.jpg [thumb image create]
$app->get('/img/{thumb}/{model}/{filename}', 'ImagesController@create');

$api->version(['v1'], function ($api) use ($app) {

```
$api->group(['prefix' => 'admin', 'namespace' => 'App\Http\Controllers\Admin'], function () use ($api) {
    // cities admin side
    $api->delete('cities/{id}', 'AdminCitiesController@destroy');

    .........
```

**Comment by bryannielsen** [comment]
I think I'm hitting this too, more generally any route that uses parameters (simple or regex) returns a 404.  

When I remove Dingo service providers and routes the parameters are matched successfully.  I'm using Lumen 5.1

**Comment by icibotaru** [comment]
This should be fixed, i want to use Lumen Route Parameters for front-end and Dingo Api Routing for back-end, but now my front-end returns 404 on everything that contains a required parameter.

**Comment by hskrasek** [comment]
@icibotaru and @banandam, are y'all still experiencing this issue with the latest version of the package?

**Comment by maesklaas** [comment]
Is it possible to fix this issue? I have trouble using dingo for lumen combined with clockwork. @itsgoingd had a look and found the problem. He referenced the issue above
